# Generated by Django 5.1.5 on 2025-02-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_category_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
