# Generated by Django 5.1.5 on 2025-02-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_category_description_tag_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Website', max_length=100, verbose_name='Site Name')),
                ('site_description', models.TextField(verbose_name='Site Description')),
                ('site_tagline', models.CharField(verbose_name='Site Tagline')),
                ('blog_title', models.CharField(default='My Blog', max_length=100, verbose_name='Blog Title')),
                ('blog_description', models.TextField(verbose_name='Blog Description')),
                ('blog_tagline', models.CharField(max_length=200, verbose_name='Blog Tagline')),
                ('blog_category_title', models.CharField(max_length=100, verbose_name='Category Title')),
                ('blog_category_description', models.TextField(verbose_name='Category Description')),
                ('blog_category_tagline', models.CharField(max_length=200, verbose_name='Category Tagline')),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
