# Generated by Django 5.1.5 on 2025-02-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_sitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='blog_category_description',
            field=models.TextField(default='Explore posts by category.', verbose_name='Category Description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='blog_category_tagline',
            field=models.CharField(default='Find what interests you.', max_length=200, verbose_name='Category Tagline'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='blog_category_title',
            field=models.CharField(default='Topics', max_length=100, verbose_name='Category Title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='blog_description',
            field=models.TextField(default='Latest posts and updates.', verbose_name='Blog Description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='blog_tagline',
            field=models.CharField(default='Insights & Stories', max_length=200, verbose_name='Blog Tagline'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='blog_title',
            field=models.CharField(default='Blog', max_length=100, verbose_name='Blog Title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(default='A flexible content management platform.', verbose_name='Site Description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Website', max_length=100, verbose_name='Site Name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_tagline',
            field=models.CharField(default='Your online presence, simplified.', max_length=255, verbose_name='Site Tagline'),
        ),
    ]
