# Generated by Django 5.1.5 on 2025-02-08 09:02

import cms.models.settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_sitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='image_aspect_ratio_height',
            field=models.IntegerField(default=9, help_text='Aspect ratio height value', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Aspect Ratio Height'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='image_aspect_ratio_width',
            field=models.IntegerField(default=16, help_text='Aspect ratio width value', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Aspect Ratio Width'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='image_sizes',
            field=models.JSONField(default=cms.models.settings.default_image_sizes, help_text='List of image sizes for responsive images (in pixels)', verbose_name='Image Sizes'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='image_upload_path_format',
            field=models.CharField(default='{model_name}/{year}/{month}/{day}', help_text='Format string for upload path. Available variables: {model_name}, {year}, {month}, {day}', max_length=255, verbose_name='Upload Path Format'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='image_webp_quality',
            field=models.IntegerField(default=85, help_text='WebP compression quality (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='WebP Quality'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='blog_category_description',
            field=models.TextField(default='Explore posts by category.', verbose_name='Category Description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='blog_category_tagline',
            field=models.CharField(default='Find what interests you.', max_length=200, verbose_name='Category Tagline'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='blog_category_title',
            field=models.CharField(default='Topics', max_length=100, verbose_name='Category Title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='blog_description',
            field=models.TextField(default='Latest posts and updates.', verbose_name='Blog Description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='blog_tagline',
            field=models.CharField(default='Insights & Stories', max_length=200, verbose_name='Blog Tagline'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='blog_title',
            field=models.CharField(default='Blog', max_length=100, verbose_name='Blog Title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(default='A flexible content management platform.', verbose_name='Site Description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Website', max_length=100, verbose_name='Site Name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_tagline',
            field=models.CharField(default='Your online presence, simplified.', max_length=255, verbose_name='Site Tagline'),
        ),
    ]
