# Generated by Django 5.1.5 on 2025-02-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Google Analytics tracking ID (e.g., G-XXXXXXXXXX)', max_length=50, verbose_name='Google Analytics'),
        ),
    ]
