# Generated by Django 5.1.5 on 2025-02-07 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='image_aspect_ratio_height',
            field=models.IntegerField(default=9, help_text='Aspect ratio height value', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Aspect Ratio Height'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='image_aspect_ratio_width',
            field=models.IntegerField(default=16, help_text='Aspect ratio width value', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Aspect Ratio Width'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='image_sizes',
            field=models.JSONField(default=[576, 768, 992, 1200], help_text='List of image sizes for responsive images (in pixels)', verbose_name='Image Sizes'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='image_upload_path_format',
            field=models.CharField(default='{model_name}s/{year}/{month}/{day}', help_text='Format string for upload path. Available variables: {model_name}, {year}, {month}, {day}', max_length=255, verbose_name='Upload Path Format'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='image_webp_quality',
            field=models.IntegerField(default=85, help_text='WebP compression quality (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='WebP Quality'),
        ),
    ]
