# Generated by Django 5.1.5 on 2025-02-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_sitesettings_google_analytics_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('published', 'Published')], default='draft', verbose_name='Status'),
        ),
    ]
