# Generated by Django 5.1.5 on 2025-02-07 09:05

import cms.models.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='image_sizes',
            field=models.JSONField(default=cms.models.settings.default_image_sizes, help_text='List of image sizes for responsive images (in pixels)', verbose_name='Image Sizes'),
        ),
    ]
