# Generated by Django 5.1.5 on 2025-02-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[(0, 'Draft'), (1, 'Published')], default=0, max_length=10, verbose_name='Status'),
        ),
    ]
