# Generated by Django 5.1.5 on 2025-02-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Excerpt'),
        ),
    ]
