# Generated by Django 5.1.5 on 2025-04-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_post_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Summary'),
        ),
    ]
